package server

import (
	"log"
	"net/http"
)

const ASSETS_PATH = "assets"

func Run(pathToStaticWebsite string) {
	// Serves all page assets generated by Svelte
	http.Handle("/assets/", fileServerWrapper(pathToStaticWebsite, ASSETS_PATH))

	// Home Page
	http.Handle("/", handlerFuncWrapper(pathToStaticWebsite, homeHandler))

	// Start web server in seperate blocking thread
	log.Fatal(http.ListenAndServe(":8080", nil))
}
